# Generated by Django 4.1.7 on 2023-03-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_team_leader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="cards",
            field=models.ManyToManyField(
                related_name="nonleaders", to="users.ownedcard"
            ),
        ),
    ]
