# Generated by Django 4.1.7 on 2023-03-19 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_team_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="user_data",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.userdata",
            ),
        ),
    ]
