# Generated by Django 4.1.7 on 2023-02-25 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0002_skillduration_skillprobability"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("desc", models.TextField()),
                ("skill_type", models.IntegerField()),
                ("timer", models.IntegerField()),
                (
                    "duration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.skillduration",
                    ),
                ),
                (
                    "probability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.skillprobability",
                    ),
                ),
            ],
        ),
    ]
