# Generated by Django 4.1.7 on 2023-02-26 04:18

from django.db import migrations, models


def set_evolved(apps, schema_editor):
    Card = apps.get_model("cards", "Card")
    cards = Card.objects.all()
    for card in cards:
        card.is_evolved = card.rarity % 2 == 0
    Card.objects.bulk_update(cards, ["is_evolved"])


def undo_set_evolved(apps, schema_editor):
    pass  # do nothing


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0004_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_evolved",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.RunPython(set_evolved, undo_set_evolved),
        migrations.AlterField(
            model_name="card",
            name="rarity",
            field=models.IntegerField(
                choices=[
                    (1, "N"),
                    (2, "N+"),
                    (3, "R"),
                    (4, "R+"),
                    (5, "SR"),
                    (6, "SR+"),
                    (7, "SSR"),
                    (8, "SSR+"),
                ]
            ),
        ),
    ]
