# Generated by Django 4.1.7 on 2023-02-26 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0005_card_is_evolved_alter_card_rarity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="is_evolved",
        ),
    ]
