# Generated by Django 4.1.7 on 2023-03-05 05:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0006_remove_card_is_evolved"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["id"]},
        ),
    ]
